### PR TITLE
Compute AI moves asynchronously

### PR DESCRIPTION
**Pull request by ryantrinkle**
Since GTK frequently blocks the main OS thread, you'll need to make sure you're running with at least 2 OS threads, e.g. with options like this:
ghc -threaded -with-rtsopts=-N2

### CODE REVIEW

**Comment by jeffreyrosenbluth** [comment]
Thanks !!
I give it a try and see if I have any questions.

**Comment by jeffreyrosenbluth** [comment]
Works nicely and the code is fairly straightforward. One thing I'm curious about is why reflex (and i think ghcjs.dom) depends on GTK?

**Comment by ryantrinkle** [comment]
It only depends on GTK for the desktop version; it runs in a webframe, and should work just like the ghcjs version.  Try your app out in ghci :)

**Comment by jeffreyrosenbluth** [comment]
Ah I see. It seems a shame though the ghcjs-dom depends on glib, gtk, etc. All things that are notoriously difficult to install on OSX. I wonder if it would be feasible to factor these dependencies out into another module or a least create a version of ghcjs-dom that does not have them (of course without the ability to run on the desktop). Perhaps I'll ask luite about it.

**Comment by ryantrinkle** [comment]
That should already be the case - it should only require those dependencies when built with ghc.  Are you not able to build with GHCJS on OS X?

**Comment by jeffreyrosenbluth** [comment]
No I can build with GHCJS on OS X. I was thinking of not being able to
build the reflex-dom pr i started working on using cabal. I was not sure
how to do this using the try-reflex nix install. If you can direct me on
how to do this I can probably finish it.

**Comment by jeffreyrosenbluth** [comment]
One of these days I may have to bit the bullet and dive into nix :)

**Comment by ryantrinkle** [comment]
I added https://github.com/ryantrinkle/try-reflex/blob/master/HACKING.md with a description of how to get into a shell for working on reflex or reflex-dom.

**Comment by jeffreyrosenbluth** [comment]
great, thanks

**Pull request merged**
